"ActiveCPUsinPool": "active_cpus_in_pool"
"ActivePhysicalCPUsinsystem": "active_physical_cpus_in_system"
"CapacityIncrement": "capacity_increment"
"DesiredCapacity": "desired_capacity"
"DesiredMemory": "desired_memory"
"DesiredVariableCapacityWeight": "desired_variable_capacity_weight"
"DesiredVirtualCPUs": "desired_virtual_cpus"
"EntitledCapacity": "entitled_capacity"
"EntitledCapacityofPool": "entitled_capacity_of_pool"
"HypervisorPageSize": "hypervisor_page_size"
"MaximumCapacity": "maximum_capacity"
"MaximumCapacityofPool": "maximum_capacity_of_pool"
"MaximumMemory": "maximum_memory"
"MaximumPhysicalCPUsinsystem": "maximum_physical_cpus_in_system"
"MaximumVirtualCPUs": "maximum_virtual_cpus"
"MemoryGroupIDofLPAR": "memory_group_id_of_lpar"
"MemoryMode": "memory_mode"
"MemoryPoolID": "memory_pool"
"MinimumCapacity": "minimum_capacity"
"MinimumMemory": "minimum_memory"
"MinimumVirtualCPUs": "minimum_virtual_cpus"
"Mode": "mode"
"NodeName": "node_name"
"OnlineMemory": "online_memory"
"OnlineVirtualCPUs": "online_virtual_cpus"
"PartitionGroup-ID": "partition_group"
"PartitionName": "partition_name"
"PartitionNumber": "partition_number"
"PhysicalCPUPercentage": "physical_cpu_percentage"
"PhysicalMemoryinthePool": "physical_memory_in_the_pool"
"PowerSavingMode": "power_saving_mode"
"SharedPhysicalCPUsinsystem": "shared_physical_cpus_in_system"
"SharedPoolID": "shared_pool"
"TargetMemoryExpansionFactor": "target_memory_expansion_factor"
"TargetMemoryExpansionSize": "target_memory_expansion_size"
"TotalI/OMemoryEntitlement": "total_io_memory_entitlement"
"Type": "lpar_type"
"UnallocatedCapacity": "unallocated_capacity"
"UnallocatedI/OMemoryentitlement": "unallocated_io_memory_entitlement"
"UnallocatedVariableMemoryCapacityWeight": "unallocated_variable_memory_capacity_weight"
"UnallocatedWeight": "unallocated_weight"
"VariableCapacityWeight": "variable_capacity_weight"
"VariableMemoryCapacityWeight": "variable_memory_capacity_weight"

