require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AixAlertsController do

  # This should return the minimal set of attributes required to create a valid
  # AixAlert. As you add validations to AixAlert, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "alert_type" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AixAlertsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all aix_alerts as @aix_alerts" do
      aix_alert = AixAlert.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aix_alerts).should eq([aix_alert])
    end
  end

  describe "GET show" do
    it "assigns the requested aix_alert as @aix_alert" do
      aix_alert = AixAlert.create! valid_attributes
      get :show, {:id => aix_alert.to_param}, valid_session
      assigns(:aix_alert).should eq(aix_alert)
    end
  end

  describe "GET new" do
    it "assigns a new aix_alert as @aix_alert" do
      get :new, {}, valid_session
      assigns(:aix_alert).should be_a_new(AixAlert)
    end
  end

  describe "GET edit" do
    it "assigns the requested aix_alert as @aix_alert" do
      aix_alert = AixAlert.create! valid_attributes
      get :edit, {:id => aix_alert.to_param}, valid_session
      assigns(:aix_alert).should eq(aix_alert)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AixAlert" do
        expect {
          post :create, {:aix_alert => valid_attributes}, valid_session
        }.to change(AixAlert, :count).by(1)
      end

      it "assigns a newly created aix_alert as @aix_alert" do
        post :create, {:aix_alert => valid_attributes}, valid_session
        assigns(:aix_alert).should be_a(AixAlert)
        assigns(:aix_alert).should be_persisted
      end

      it "redirects to the created aix_alert" do
        post :create, {:aix_alert => valid_attributes}, valid_session
        response.should redirect_to(AixAlert.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aix_alert as @aix_alert" do
        # Trigger the behavior that occurs when invalid params are submitted
        AixAlert.any_instance.stub(:save).and_return(false)
        post :create, {:aix_alert => { "alert_type" => "invalid value" }}, valid_session
        assigns(:aix_alert).should be_a_new(AixAlert)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AixAlert.any_instance.stub(:save).and_return(false)
        post :create, {:aix_alert => { "alert_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aix_alert" do
        aix_alert = AixAlert.create! valid_attributes
        # Assuming there are no other aix_alerts in the database, this
        # specifies that the AixAlert created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AixAlert.any_instance.should_receive(:update_attributes).with({ "alert_type" => "MyString" })
        put :update, {:id => aix_alert.to_param, :aix_alert => { "alert_type" => "MyString" }}, valid_session
      end

      it "assigns the requested aix_alert as @aix_alert" do
        aix_alert = AixAlert.create! valid_attributes
        put :update, {:id => aix_alert.to_param, :aix_alert => valid_attributes}, valid_session
        assigns(:aix_alert).should eq(aix_alert)
      end

      it "redirects to the aix_alert" do
        aix_alert = AixAlert.create! valid_attributes
        put :update, {:id => aix_alert.to_param, :aix_alert => valid_attributes}, valid_session
        response.should redirect_to(aix_alert)
      end
    end

    describe "with invalid params" do
      it "assigns the aix_alert as @aix_alert" do
        aix_alert = AixAlert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AixAlert.any_instance.stub(:save).and_return(false)
        put :update, {:id => aix_alert.to_param, :aix_alert => { "alert_type" => "invalid value" }}, valid_session
        assigns(:aix_alert).should eq(aix_alert)
      end

      it "re-renders the 'edit' template" do
        aix_alert = AixAlert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AixAlert.any_instance.stub(:save).and_return(false)
        put :update, {:id => aix_alert.to_param, :aix_alert => { "alert_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aix_alert" do
      aix_alert = AixAlert.create! valid_attributes
      expect {
        delete :destroy, {:id => aix_alert.to_param}, valid_session
      }.to change(AixAlert, :count).by(-1)
    end

    it "redirects to the aix_alerts list" do
      aix_alert = AixAlert.create! valid_attributes
      delete :destroy, {:id => aix_alert.to_param}, valid_session
      response.should redirect_to(aix_alerts_url)
    end
  end

end
