require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HealthChecksController do

  # This should return the minimal set of attributes required to create a valid
  # HealthCheck. As you add validations to HealthCheck, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HealthChecksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all health_checks as @health_checks" do
      health_check = HealthCheck.create! valid_attributes
      get :index, {}, valid_session
      assigns(:health_checks).should eq([health_check])
    end
  end

  describe "GET show" do
    it "assigns the requested health_check as @health_check" do
      health_check = HealthCheck.create! valid_attributes
      get :show, {:id => health_check.to_param}, valid_session
      assigns(:health_check).should eq(health_check)
    end
  end

  describe "GET new" do
    it "assigns a new health_check as @health_check" do
      get :new, {}, valid_session
      assigns(:health_check).should be_a_new(HealthCheck)
    end
  end

  describe "GET edit" do
    it "assigns the requested health_check as @health_check" do
      health_check = HealthCheck.create! valid_attributes
      get :edit, {:id => health_check.to_param}, valid_session
      assigns(:health_check).should eq(health_check)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HealthCheck" do
        expect {
          post :create, {:health_check => valid_attributes}, valid_session
        }.to change(HealthCheck, :count).by(1)
      end

      it "assigns a newly created health_check as @health_check" do
        post :create, {:health_check => valid_attributes}, valid_session
        assigns(:health_check).should be_a(HealthCheck)
        assigns(:health_check).should be_persisted
      end

      it "redirects to the created health_check" do
        post :create, {:health_check => valid_attributes}, valid_session
        response.should redirect_to(HealthCheck.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved health_check as @health_check" do
        # Trigger the behavior that occurs when invalid params are submitted
        HealthCheck.any_instance.stub(:save).and_return(false)
        post :create, {:health_check => { "name" => "invalid value" }}, valid_session
        assigns(:health_check).should be_a_new(HealthCheck)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HealthCheck.any_instance.stub(:save).and_return(false)
        post :create, {:health_check => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested health_check" do
        health_check = HealthCheck.create! valid_attributes
        # Assuming there are no other health_checks in the database, this
        # specifies that the HealthCheck created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HealthCheck.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => health_check.to_param, :health_check => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested health_check as @health_check" do
        health_check = HealthCheck.create! valid_attributes
        put :update, {:id => health_check.to_param, :health_check => valid_attributes}, valid_session
        assigns(:health_check).should eq(health_check)
      end

      it "redirects to the health_check" do
        health_check = HealthCheck.create! valid_attributes
        put :update, {:id => health_check.to_param, :health_check => valid_attributes}, valid_session
        response.should redirect_to(health_check)
      end
    end

    describe "with invalid params" do
      it "assigns the health_check as @health_check" do
        health_check = HealthCheck.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HealthCheck.any_instance.stub(:save).and_return(false)
        put :update, {:id => health_check.to_param, :health_check => { "name" => "invalid value" }}, valid_session
        assigns(:health_check).should eq(health_check)
      end

      it "re-renders the 'edit' template" do
        health_check = HealthCheck.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HealthCheck.any_instance.stub(:save).and_return(false)
        put :update, {:id => health_check.to_param, :health_check => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested health_check" do
      health_check = HealthCheck.create! valid_attributes
      expect {
        delete :destroy, {:id => health_check.to_param}, valid_session
      }.to change(HealthCheck, :count).by(-1)
    end

    it "redirects to the health_checks list" do
      health_check = HealthCheck.create! valid_attributes
      delete :destroy, {:id => health_check.to_param}, valid_session
      response.should redirect_to(health_checks_url)
    end
  end

end
