require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SanAlertsController do

  # This should return the minimal set of attributes required to create a valid
  # SanAlert. As you add validations to SanAlert, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "alert_type" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SanAlertsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all san_alerts as @san_alerts" do
      san_alert = SanAlert.create! valid_attributes
      get :index, {}, valid_session
      assigns(:san_alerts).should eq([san_alert])
    end
  end

  describe "GET show" do
    it "assigns the requested san_alert as @san_alert" do
      san_alert = SanAlert.create! valid_attributes
      get :show, {:id => san_alert.to_param}, valid_session
      assigns(:san_alert).should eq(san_alert)
    end
  end

  describe "GET new" do
    it "assigns a new san_alert as @san_alert" do
      get :new, {}, valid_session
      assigns(:san_alert).should be_a_new(SanAlert)
    end
  end

  describe "GET edit" do
    it "assigns the requested san_alert as @san_alert" do
      san_alert = SanAlert.create! valid_attributes
      get :edit, {:id => san_alert.to_param}, valid_session
      assigns(:san_alert).should eq(san_alert)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SanAlert" do
        expect {
          post :create, {:san_alert => valid_attributes}, valid_session
        }.to change(SanAlert, :count).by(1)
      end

      it "assigns a newly created san_alert as @san_alert" do
        post :create, {:san_alert => valid_attributes}, valid_session
        assigns(:san_alert).should be_a(SanAlert)
        assigns(:san_alert).should be_persisted
      end

      it "redirects to the created san_alert" do
        post :create, {:san_alert => valid_attributes}, valid_session
        response.should redirect_to(SanAlert.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved san_alert as @san_alert" do
        # Trigger the behavior that occurs when invalid params are submitted
        SanAlert.any_instance.stub(:save).and_return(false)
        post :create, {:san_alert => { "alert_type" => "invalid value" }}, valid_session
        assigns(:san_alert).should be_a_new(SanAlert)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SanAlert.any_instance.stub(:save).and_return(false)
        post :create, {:san_alert => { "alert_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested san_alert" do
        san_alert = SanAlert.create! valid_attributes
        # Assuming there are no other san_alerts in the database, this
        # specifies that the SanAlert created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SanAlert.any_instance.should_receive(:update_attributes).with({ "alert_type" => "MyString" })
        put :update, {:id => san_alert.to_param, :san_alert => { "alert_type" => "MyString" }}, valid_session
      end

      it "assigns the requested san_alert as @san_alert" do
        san_alert = SanAlert.create! valid_attributes
        put :update, {:id => san_alert.to_param, :san_alert => valid_attributes}, valid_session
        assigns(:san_alert).should eq(san_alert)
      end

      it "redirects to the san_alert" do
        san_alert = SanAlert.create! valid_attributes
        put :update, {:id => san_alert.to_param, :san_alert => valid_attributes}, valid_session
        response.should redirect_to(san_alert)
      end
    end

    describe "with invalid params" do
      it "assigns the san_alert as @san_alert" do
        san_alert = SanAlert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SanAlert.any_instance.stub(:save).and_return(false)
        put :update, {:id => san_alert.to_param, :san_alert => { "alert_type" => "invalid value" }}, valid_session
        assigns(:san_alert).should eq(san_alert)
      end

      it "re-renders the 'edit' template" do
        san_alert = SanAlert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SanAlert.any_instance.stub(:save).and_return(false)
        put :update, {:id => san_alert.to_param, :san_alert => { "alert_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested san_alert" do
      san_alert = SanAlert.create! valid_attributes
      expect {
        delete :destroy, {:id => san_alert.to_param}, valid_session
      }.to change(SanAlert, :count).by(-1)
    end

    it "redirects to the san_alerts list" do
      san_alert = SanAlert.create! valid_attributes
      delete :destroy, {:id => san_alert.to_param}, valid_session
      response.should redirect_to(san_alerts_url)
    end
  end

end
